export { default as DatePicker } from "antd/es/date-picker";
import "antd/es/date-picker/style/css";
export { default as Button } from "antd/es/button";
import "antd/es/button/style/css";
export { default as Input } from "antd/es/input";
import "antd/es/input/style/css";
export { default as Tabs } from "antd/es/tabs";
import "antd/es/tabs/style/css";
export { default as Table } from "antd/es/Table";
import "antd/es/Table/style/css";
